import type { Job } from '@open-resource/shared'
import type { ApplicantApplication } from './types'

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    created_by: 'hr-user-1',
    title: 'Senior Frontend Engineer',
    description: `We are looking for a Senior Frontend Engineer to join our growing team.\n\nYou will be responsible for building and maintaining our web applications using React, TypeScript, and modern tooling.\n\nRequirements:\n- 4+ years of React experience\n- Strong TypeScript skills\n- Experience with performance optimization\n- Familiarity with design systems`,
    location: 'San Francisco, CA',
    job_type: 'hybrid',
    status: 'active',
    application_deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    shortlist_cutoff: 5,
    scoring_weights: {
      technical_skills: 40,
      experience: 25,
      projects: 20,
      education: 8,
      communication: 7,
    },
    jd_parsed: {
      role_title: 'Senior Frontend Engineer',
      seniority: 'senior',
      must_have_skills: ['React', 'TypeScript', 'CSS'],
      nice_to_have_skills: ['GraphQL', 'Testing'],
      experience_years_min: 4,
      proposed_weights: {
        technical_skills: 40,
        experience: 25,
        projects: 20,
        education: 8,
        communication: 7,
      },
      weight_reasoning: 'Technical skills weighted highest due to hands-on engineering role.',
    },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    hired_at: null,
    hiring_summary: null,
  },
  {
    id: 'job-2',
    created_by: 'hr-user-1',
    title: 'Backend Python Engineer',
    description: `Join our backend team to build scalable APIs and data pipelines.\n\nYou'll work with FastAPI, PostgreSQL, and cloud infrastructure.\n\nRequirements:\n- 3+ years Python experience\n- FastAPI or Django REST framework\n- SQL proficiency\n- Docker/Kubernetes basics`,
    location: 'Remote',
    job_type: 'remote',
    status: 'active',
    application_deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    shortlist_cutoff: 3,
    scoring_weights: {
      technical_skills: 45,
      experience: 30,
      projects: 15,
      education: 5,
      communication: 5,
    },
    jd_parsed: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    hired_at: null,
    hiring_summary: null,
  },
  {
    id: 'job-3',
    created_by: 'hr-user-1',
    title: 'Product Designer',
    description: `We're looking for a Product Designer who can own the full design process from research to high-fidelity prototypes.\n\nRequirements:\n- Figma proficiency\n- Experience with design systems\n- User research experience\n- Portfolio of shipped products`,
    location: 'New York, NY',
    job_type: 'onsite',
    status: 'active',
    application_deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    shortlist_cutoff: 4,
    scoring_weights: {
      technical_skills: 25,
      experience: 30,
      projects: 30,
      education: 7,
      communication: 8,
    },
    jd_parsed: null,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    closed_at: null,
    hired_at: null,
    hiring_summary: null,
  },
]

export const mockApplications: ApplicantApplication[] = [
  {
    id: 'app-1',
    job_id: 'job-2',
    job_title: 'Backend Python Engineer',
    resume_filename: 'resume.pdf',
    cover_note: 'I am very excited about this opportunity.',
    status: 'shortlisted',
    rank: 2,
    submitted_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    scores: {
      technical_score: 88,
      experience_score: 82,
      project_score: 91,
      education_score: 75,
      communication_score: 79,
      weighted_total: 86,
      verdict: 'shortlisted',
      applicant_feedback:
        'Your application demonstrates strong technical skills, particularly in Python and API development. Your project portfolio shows relevant experience building production-grade systems. Consider deepening your knowledge of container orchestration to strengthen future applications.',
    },
  },
  {
    id: 'app-2',
    job_id: 'job-1',
    job_title: 'Senior Frontend Engineer',
    resume_filename: 'resume.pdf',
    cover_note: 'I love frontend engineering.',
    status: 'reviewing',
    rank: null,
    submitted_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    scores: null,
  },
]
